title: How to write a JavaScript function
tagline: Learn how to write a good JavaScript function
description: Mini course to learn best practices of creating good JavaScript functions

template:
  name: js-functions
  repo: js-functions-template

# `before` block
# Actions to take place after the learner registers, but before they start interacting with their repo

before:
- type: respond
  with: 01_first-response.md

steps:
- title: Create an empty function
  description: Checking out the basic syntax
  event: push
  actions: # a list of the actions that will occur when the step is triggered by an event
  - type: # the type of action, full list at https://lab.github.com/docs/actions

- title: Naming the function properly
 description: Good naming is important to write readable code
 event: push
 actions: # a list of the actions that will occur when the step is triggered by an event
 - type: # the type of action, full list at https://lab.github.com/docs/actions

- title: Retrun a value
 description: Returning a value allow you to implement algorithms
 event: status
 actions: # a list of the actions that will occur when the step is triggered by an event
 - type: # the type of action, full list at https://lab.github.com/docs/actions

- title: Accepting parameters
 description: Functions can use input values to process them
 event: status
 actions: # a list of the actions that will occur when the step is triggered by an event
 - type: # the type of action, full list at https://lab.github.com/docs/actions

- title: 3 functions
 description: Implementing an algorithm
 event: pull_request.synchronize
 actions: # a list of the actions that will occur when the step is triggered by an event
 - type: # the type of action, full list at https://lab.github.com/docs/actions

